<?php

namespace Siciarek\SymfonyCommonBundle\Entity;

/**
 * AddressBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressBookRepository extends \Doctrine\ORM\EntityRepository
{
}
