<?php

namespace Siciarek\SymfonyCommonBundle\Entity;

/**
 * ContactListEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactListEntryRepository extends \Doctrine\ORM\EntityRepository
{
}
