<?php

namespace Siciarek\SymfonyCommonBundle\Entity;

/**
 * DocumentFolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentFolderRepository extends \Doctrine\ORM\EntityRepository
{
}
