<?php

namespace Siciarek\SymfonyCommonBundle\Entity;

/**
 * ParameterIndexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParameterIndexRepository extends \Doctrine\ORM\EntityRepository
{
}
